### ISSUE TITLE
0.6 Suggestions

### ISSUE THREAD

**Issue by bluemonster122** [lilmoefow/MFCraft#3]
tails =D
I want my ears

**Comment by bluemonster122** [comment]
Maybe add MFFS, but maybe add a crafting recipe for the things if its not the calclavia one.

**Comment by DeathwishXx** [comment]
MFFS is extremely buggy and I don't believe it's for the correct version.

**Comment by lilmoefow** [comment]
-Remove The Erebus
-Remove Storage Drawers: The Erebus

-Add Et Futurum
-Add Secret Rooms
-Add Tails

-Update Botania(again)

**Comment by Occidentas** [comment]
Factorization should be added. Seems pretty cool.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284592-factorization-0-8-95
