### ISSUE TITLE
0.6 Update

### ISSUE THREAD

**Issue by lilmoefow** [lilmoefow/MFCraft#5]
(Done)
-Remove Chisel 2
-Remove Lantea Craft
-Remove The Erebus
-Remove Storage Drawers: The Erebus

-Add Better Boat
-Add Better Foliage
-Add Et Futurum
-Add Logistics Pipes
-Add Secret Rooms
-Add Similsax Transtructors
-Add Statues
-Add Tails
-Add Twilight Forest
-Add Chisel 2.5.0

-Update Botania(again)(AGAIN)
-Update CoFH Tweaks
-Update DecoCraft
-Update Extra Utilities

-Update Mine Factory Reloaded

-Config Change JABBA
 -Added Structural Upgrades
-Config Change Botania
 -Removed Item Conflits
 -Other Surprises

(TO DO)
-Update MoreChisels

**Comment by bluemonster122** [comment]
Other suprises? >.<
